# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:

- stage: Dotnet
  jobs:
  - job: RestoreBuildTest
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:

    - task: UseDotNet@2
      displayName: 'Sdk'
      inputs:
        packageType: sdk
        version: 3.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        feedsToUse: 'select'    
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '**/*Test/*.csproj'
        arguments: '--configuration Release'

# - stage: Docker
#   jobs:
#   - job: BuildAndPushToHub
#     steps:    

#     - task: Docker@2
#       displayName: BuildAndPush
#       inputs:
#         containerRegistry: '$(DockerRegistry)'
#         repository: '$(DockerRepo)'
#         command: 'buildAndPush'
#         Dockerfile: '**/Dockerfile'